function [path, OPEN] = A_star_search(map,MAX_X,MAX_Y)
%%
%This part is about map/obstacle/and other settings
    %pre-process the grid map, add offset
    size_map = size(map,1);
    Y_offset = 0;
    X_offset = 0;
    
    %Define the 2D grid map array.
    %Obstacle=-1, Target = 0, Start=1
    MAP=2*(ones(MAX_X,MAX_Y));
    
    %Initialize MAP with location of the target
    xval=floor(map(size_map, 1)) + X_offset;
    yval=floor(map(size_map, 2)) + Y_offset;
    xTarget=xval;
    yTarget=yval;
    MAP(xval,yval)=0;
    
    %Initialize MAP with location of the obstacle
    for i = 2: size_map-1
        xval=floor(map(i, 1)) + X_offset;
        yval=floor(map(i, 2)) + Y_offset;
        MAP(xval,yval)=-1;
    end 
    
    %Initialize MAP with location of the start point
    %初始起点的x值y值将会是1
    xval=floor(map(1, 1)) + X_offset;
    yval=floor(map(1, 2)) + Y_offset;
    xStart=xval;
    yStart=yval;
    MAP(xval,yval)=1;

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %LISTS USED FOR ALGORITHM
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %OPEN LIST STRUCTURE
    %--------------------------------------------------------------------------
    %IS ON LIST 1/0 |X val |Y val |Parent X val |Parent Y val |h(n) |g(n)|f(n)|
    %--------------------------------------------------------------------------
    OPEN=[];
    %CLOSED LIST STRUCTURE
    %--------------
    %X val | Y val |
    %--------------
    % CLOSED=zeros(MAX_VAL,2);
    CLOSED=[];

    %Put all obstacles on the Closed list
    k=1;%Dummy counter
    for i=1:MAX_X
        for j=1:MAX_Y
            if(MAP(i,j) == -1) %Obstacle
                CLOSED(k,1)=i;
                CLOSED(k,2)=j;
                k=k+1;
            end
        end
    end
    CLOSED_COUNT=size(CLOSED,1);
    %set the starting node as the first node
    xNode=xval;
    yNode=yval;
    OPEN_COUNT=1;
    goal_distance=distance(xNode,yNode,xTarget,yTarget);
    path_cost=0;

    %--------------------------------------------------------------------------
    %IS ON LIST 1/0 |X val |Y val |Parent X val |Parent Y val |h(n) |g(n)|f(n)|
    %--------------------------------------------------------------------------
    OPEN(OPEN_COUNT,:)=insert_open(xNode,yNode,xNode,yNode,goal_distance,path_cost,goal_distance);
    % take it off the open list and put it on the closed list
    OPEN(OPEN_COUNT,1)=0;

    %--------------
    %X val | Y val |
    %--------------
    CLOSED_COUNT=CLOSED_COUNT+1;
    CLOSED(CLOSED_COUNT,1)=xNode;
    CLOSED(CLOSED_COUNT,2)=yNode;
    % flag to indicate if path is found or not
    NoPath=1;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% START ALGORITHM
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    exit_flag = 0;
    while(~exit_flag) 
        exp_array = expand_array(xNode,yNode,path_cost,xTarget,yTarget,CLOSED,MAX_X,MAX_Y);
        
        % get the number of expanded nodes
        exp_count=size(exp_array,1);
        %Insert each CORRECT expanded node to the OPEN list
        for i=1:exp_count
            for j=1:CLOSED_COUNT
                if (exp_array(i,1) == CLOSED(j,1) && exp_array(i,2) == CLOSED(j,2))
                    % this successor is on the CLOSED list, do not add to OPEN
                    break;
                else % add it into the OPEN 
                    OPEN_COUNT=OPEN_COUNT+1;
                    OPEN(OPEN_COUNT,:)=insert_open(exp_array(i,1),exp_array(i,2),xNode,yNode,exp_array(i,3),exp_array(i,4),exp_array(i,5));
                    OPEN(OPEN_COUNT,1)=1; %mark as on the OPEN list
                end
            end
        end

        %Find the node with the minimum fn value from the OPEN list
        i_min = min_fn(OPEN,OPEN_COUNT,xTarget,yTarget);
        xNode = OPEN(i_min,2);
        yNode = OPEN(i_min,3);

        % take it off the open list and put it on the closed list
        OPEN(i_min,1)=0;
        CLOSED_COUNT=CLOSED_COUNT+1;
        CLOSED(CLOSED_COUNT,1)=xNode;
        CLOSED(CLOSED_COUNT,2)=yNode;
        
        %Check if the OPEN is empty
        exit_flag = isEmpty(OPEN,OPEN_COUNT);

        %Check if we have reached the goal
        if (xNode == xTarget && yNode == yTarget)
            NoPath = 0;
            break;
        end

    end %End of While Loop
    
    %Once algorithm has run The optimal path is generated by starting of at the
    %last node(if it is the target node) and then identifying its parent node
    %until it reaches the start node.This is the optimal path
    
    %How to get the optimal path after A_star search?
    %please finish it

    path = [];
    if (NoPath == 0) %Path has been found
        path_index = 1;
        path(path_index,1) = xNode;
        path(path_index,2) = yNode;
        while ~(xNode == xStart && yNode == yStart)
            n_index = node_index(OPEN,xNode,yNode);
            xNode = OPEN(n_index,4); %Parent X val
            yNode = OPEN(n_index,5); %Parent Y val
            path_index = path_index + 1;
            path(path_index,1) = xNode;
            path(path_index,2) = yNode;
        end
        %Reverse the path to get from start to target
        path = flipud(path);
    else
        disp('No Path Found');
    end
end
